---
title: "Linear and logist regression analysis to inverse learning poverty"
author: Geiser C. Challco <geiser@alumni.usp.br>
comment: This file is automatically generate by Shiny-Statistic app (https://statistic.geiser.tech/)
         Author - Geiser C. Challco <geiser@alumni.usp.br>
         
         Shiny-Statistic is distributed in the hope that it will be useful,
         but WITHOUT ANY WARRANTY; without even the implied warranty of
         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         GNU General Public License for more details.
         
         You should have received a copy of the GNU General Public License.
         If not, see <https://www.gnu.org/licenses/>.
output:
  github_document:
    toc: true
  html_document:
    toc: true
  word_document:
    toc: true
fontsize: 10pt
---

```{r setup, include=FALSE}
## Install and Load Packages and functions
wants <- c('readxl','dplyr')
has <- wants %in% rownames(installed.packages())
if (any(!has)) install.packages(wants[!has])


get_data <- function(dat, grp, is.mean = F) {
  library(dplyr)

  years <- sort(unique(dat$year))
  dat2 <- do.call(rbind, lapply(years, FUN = function(year) {
    values <- dat$inv.value[which(dat$IncomeGroup == grp & dat$year ==year)]
    values <- values[!is.na(values)]
    if (is.mean) {
      data.frame(year=as.integer(year), INV.LPV.PRIM=mean(values))
    } else {
      do.call(rbind, lapply(values, FUN = function(val) {
        data.frame(year=as.integer(year), INV.LPV.PRIM=val)
      }))
    }
  }))

  return(dat2)
}


library(readxl)
library(dplyr)
library(aomisc)
```

```{r, include=FALSE, purl=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE)
defaultW <- getOption("warn")
options(warn = -1)
```

## Initial Variables and Data

```{r}
dat <- read_excel("../data/lpv_edstats_update2021.xlsx", sheet = "LPV")
dat[["inv.value"]] <- 100-dat$value

lmdls <- c()
smdls <- c()

income_grp <- unique(dat$IncomeGroup)
(income_grp <- income_grp[!is.na(income_grp)])
```

## Calculating data with mean values

```{r}
df <- get_data(dat, income_grp[1], is.mean = T)

dat[dat$IncomeGroup == income_grp[1], c("year","inv.value")]
for (i in 2:length(income_grp)) {
  grp = income_grp[i]
  df <- merge(df, get_data(dat, grp, is.mean = T), by="year", suffixes = c(income_grp[i-1], grp))
}
colnames(df) <- c("year",income_grp)

knitr::kable(df)
```

## Linear Regression

### Linear regression for high income countries

```{r}
grp = income_grp[3]
dat2 <- get_data(dat, grp)

fit <- lm(INV.LPV.PRIM ~ year, data=dat2)

smdls[[grp]] <- fit
summary(fit)
```


```{r, dpi=300, fig.width=12, fig.height=8}
pyear <- seq(min(dat2$year), 2030, 1)
plot(dat2, xlim = c(min(pyear), max(pyear)), ylim = c(0,100),
     pch=16, col="blue", main = grp, xaxt='n',yaxt='n', cex = 0.5)
axis(1, at = seq(min(pyear), max(pyear), 1), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)
axis(2, at = seq(0, 140, 10), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)

matlines(pyear, predict(fit, newdata=list(year=pyear), interval="confidence"), lwd=1.25)
```

### Linear regression for upper middle income countries

```{r}
grp = income_grp[2]
dat2 <- get_data(dat, grp)

fit <- lm(INV.LPV.PRIM ~ year, data=dat2)
smdls[[grp]] <- fit
summary(fit)
```

```{r, dpi=300, fig.width=12, fig.height=8}
pyear <- seq(min(dat2$year), 2030, 1)
plot(dat2, xlim = c(min(pyear), max(pyear)), ylim = c(0,140),
     pch=16, col="blue", main = grp, xaxt='n',yaxt='n', cex = 0.5)
axis(1, at = seq(min(pyear), max(pyear), 1), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)
axis(2, at = seq(0, 140, 10), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)

matlines(pyear, predict(fit, newdata=list(year=pyear), interval="confidence"), lwd=1.25)
```

### Linear regression for lower middle income countries

```{r}
grp = income_grp[4]
dat2 <- get_data(dat, grp)

fit <- lm(INV.LPV.PRIM ~ year, data=dat2)
smdls[[grp]] <- fit
summary(fit)
```

```{r, dpi=300, fig.width=12, fig.height=8}
pyear <- seq(min(dat2$year), 2030, 1)
plot(dat2, xlim = c(min(pyear), max(pyear)), ylim = c(0,140),
     pch=16, col="blue", main = grp, xaxt='n',yaxt='n', cex = 0.5)
axis(1, at = seq(min(pyear), max(pyear), 1), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)
axis(2, at = seq(0, 140, 10), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)

matlines(pyear, predict(fit, newdata=list(year=pyear), interval="confidence"), lwd=1.25)
```

### Linear regression for low income countries

```{r}
grp = income_grp[1]
dat2 <- get_data(dat, grp)

fit <- lm(INV.LPV.PRIM ~ year, data=dat2)
smdls[[grp]] <- fit
summary(fit)
```


```{r, dpi=300, fig.width=12, fig.height=8}
pyear <- seq(min(dat2$year), 2030, 1)
plot(dat2, xlim = c(min(pyear), max(pyear)), ylim = c(0,100),
     pch=16, col="blue", main = grp, xaxt='n',yaxt='n', cex = 0.5)
axis(1, at = seq(min(pyear), max(pyear), 1), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)
axis(2, at = seq(0, 100, 10), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)

matlines(pyear, predict(fit, newdata=list(year=pyear), interval="confidence"), lwd=1.25)
```

### Summary of logistic regression with average values

```{r, dpi=300, fig.width=12, fig.height=8}
pyear <- seq(min(dat$year), 2030, 1)
plot(x=pyear, y=c(), xlim = c(min(pyear), max(pyear)), ylim=c(0,100),
     ylab = "INV.LPV.PRIM", xlab = "year", xaxt='n',yaxt='n')
axis(1, at = seq(min(pyear),max(pyear), 5), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)
axis(2, at = seq(0, 100, 5), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)


colors <- c("red","green","blue","orange")
names(colors) <- income_grp
for (grp in income_grp) {
  gdat <- get_data(dat, grp, is.mean = T)
  points(x=gdat$year, y=gdat$INV.LPV.PRIM, pch=16, col=colors[grp], xaxt='n', yaxt='n', cex=0.75)
  matlines(pyear, predict(smdls[[grp]], newdata=list(year=pyear), interval="confidence"), lwd=2)
}
legend("bottomright", legend=c("low income","upper middle income","high income","lower middle income"),
       col=colors, lty=0,  cex = 0.75, bg = "transparent", pch=16, box.lty=0)
```

```{r, dpi=300, fig.width=12, fig.height=8}
pyear <- seq(min(dat$year), 2030, 1)
plot(x=pyear, y=c(), xlim = c(min(pyear), max(pyear)), ylim=c(0,100),
     ylab = "INV.LPV.PRIM", xlab = "year", xaxt='n',yaxt='n')
axis(1, at = seq(min(pyear),max(pyear), 1), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)
axis(2, at = seq(0, 100, 5), tck = 1, lty = 4, col = "lightgray", lwd = 0.75)

colors <- c("red","green","blue","orange")
names(colors) <- income_grp
for (grp in income_grp) {
  gdat <- get_data(dat, grp, is.mean = F)
  points(x=gdat$year, y=gdat$INV.LPV.PRIM, pch=16, col=as.character(colors[grp]), xaxt='n', yaxt='n', cex=0.5)
  matlines(pyear, col = colors[grp], predict(smdls[[grp]], newdata=list(year=pyear), interval="confidence"), lwd=2)
}
legend("bottomright", legend=c("low income","upper middle income","high income","lower middle income"),
       col=colors, lty=0,  cex = 0.75, bg = "transparent", pch=16, box.lty=0)
```

```{r include=FALSE, echo=FALSE, purl=FALSE}
options(warn = defaultW)
#knitr::purl("code/regression_lpv.Rmd", "code/regression_lpv.R", documentation = 2)
```
